## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/api/*"
  to = "http://guarded-cove-46425.herokuapp.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
